.PHONY: clean cleaner

all:
	python3 ../../support/tutorial_tools/notebook/process_notebook.py deposition

clean:
	rm -f deposition.md Doxyfile
	rm -rf html

cleaner:
	rm -f deposition.ipynb deposition.py deposition.md Doxyfile
	rm -rf html

